### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/practica-6-practica-de-calidad-metricas-con-testrail-turisteando-por-mexico#1]
[TESTCASE.pdf](https://github.com/SistemasTecTlaxiaco/practica-6-practica-de-calidad-metricas-con-testrail-turisteando-por-mexico/files/12834641/TESTCASE.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
